// 카드 배경과 테두리 색상
export const typeCardColorClasses: { [key: string]: string } = {
  normal: "bg-normal-light border-normal",
  fire: "bg-fire-light border-fire",
  water: "bg-water-light border-water",
  electric: "bg-electric-light border-electric",
  grass: "bg-grass-light border-grass",
  ice: "bg-ice-light border-ice",
  fighting: "bg-fighting-light border-fighting",
  poison: "bg-poison-light border-poison",
  ground: "bg-ground-light border-ground",
  flying: "bg-flying-light border-flying",
  psychic: "bg-psychic-light border-psychic",
  bug: "bg-bug-light border-bug",
  rock: "bg-rock-light border-rock",
  ghost: "bg-ghost-light border-ghost",
  dragon: "bg-dragon-light border-dragon",
  dark: "bg-dark-light border-dark",
  steel: "bg-steel-light border-steel",
  fairy: "bg-fairy-light border-fairy",
  none: "bg-none-light border-none",
};

// 타입 배지 배경 색상
export const typeBadgeColorClasses: { [key: string]: string } = {
  normal: "bg-normal",
  fire: "bg-fire",
  water: "bg-water",
  electric: "bg-electric",
  grass: "bg-grass",
  ice: "bg-ice",
  fighting: "bg-fighting",
  poison: "bg-poison",
  ground: "bg-ground",
  flying: "bg-flying",
  psychic: "bg-psychic",
  bug: "bg-bug",
  rock: "bg-rock",
  ghost: "bg-ghost",
  dragon: "bg-dragon",
  dark: "bg-dark",
  steel: "bg-steel",
  fairy: "bg-fairy",
  none: "bg-none",
};